services:
  - type: web
    name: notes-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    # if you already have envVars, just add the FRONTEND_ORIGIN entry below:
    envVars:
      # these 3 (and JWT_SECRET) already exist in your service; keep them “unsynced”
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false

      # 👇 add/modify this line to allow your Vercel app (and local dev if you want)
      - key: FRONTEND_ORIGIN
        value: https://notes-frontend-plum.vercel.app,http://localhost:5173
