services:
  - type: web
    name: notes-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-d2sqg7je5dus73f0sfp0-a.oregon-postgres.render.com:5432/notes_db_oo5y?sslmode=require
      - key: DB_USER
        value: notes_db_oo5y_user
      - key: DB_PASSWORD
        value: RQ0OLv9ijw8WBuUKu1KOyLIEOWdc7uVu
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_ORIGIN
        value: http://localhost:5173
